title: Gaby Jazzmin Portfolio
author: Gaby Jazzmin
email: jgabrielaj.4.f@gmail.com
description: >-
  Mostrando mi manera de ver la vida a traves del lente.

social:
  twitter: 
  facebook: gabyjazzmin
  instagram: gabyjazzmin
  github: 
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
